# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-enaprep-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::adapterremoval=2.3.0
  - conda-forge::pandas=0.25.1
  - bioconda::pysam=0.15.3